seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [256, 128, 64]
        activations: elu
    output: ACTIONS
  critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE
  critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE
  target_critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE
  target_critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers: [256, 128, 64]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: 10000  # replay buffer size


# SAC agent configuration (field names are from SAC_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/sac.html
agent:
  class: SAC
  gradient_steps: 1  # gradient steps
  batch_size: 64  # training batch size (default)
  discount_factor: 0.99  # discount factor (gamma)
  polyak: 0.005  # soft update hyperparameter (tau)
  actor_learning_rate: 1.0e-3  # actor learning rate
  critic_learning_rate: 1.0e-3  # critic learning rate
  learning_rate_scheduler: null  # learning rate scheduler class (see torch.optim.lr_scheduler)
  learning_rate_scheduler_kwargs: {}  # learning rate scheduler's kwargs (e.g. {"step_size": 1e-3})
  state_preprocessor: RunningStandardScaler  # state preprocessor class (see skrl.resources.preprocessors)
  state_preprocessor_kwargs: null  # state preprocessor's kwargs (e.g. {"size": env.observation_space})
  random_timesteps: 0  # random exploration steps
  learning_starts: 0  # learning starts after this many steps
  grad_norm_clip: 0  # clipping coefficient for the norm of the gradients
  learn_entropy: True  # learn entropy
  entropy_learning_rate: 1.0e-3  # entropy learning rate
  initial_entropy_value: 0.2  # initial entropy value
  target_entropy: null  # target entropy
  rewards_shaper: null  # rewards shaping function: Callable(reward, timestep, timesteps) -> reward
  # logging and checkpoint
  experiment:
    directory: "pickplace_direct_skrl_sac"  # experiment's parent directory
    experiment_name: ""  # experiment name
    write_interval: 100  # TensorBoard writing interval (timesteps)
    checkpoint_interval: 1000  # interval for checkpoints (timesteps)
    store_separately: False  # whether to store checkpoints separately
    wandb: False  # whether to use Weights & Biases
    wandb_kwargs:  # wandb kwargs (see https://docs.wandb.ai/ref/python/init)
      entity: a
      project: b
      sync_tensorboard: True


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 75000  # total training timesteps
  environment_info: log